mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: my-blog-datasource
    password: 123456
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
